
title: "Md Maniruzzaman Mamun"
author: "Md Maniruzzaman Mamun"
description: "University of Florida"

url: "https://md-mamun.com"
baseurl: ""

lang: "en"
permalink: /:title/
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"


# Layout
show_excerpts: false
show_frame: true
show_sidebar: true
minimal: true  

# Menu
navigation:
  - { title: "About", url: "/", icon: user }
  - { title: "Research", url: "/research/", icon: book }
  - { title: "Teaching", url: "/teaching/", icon: chalkboard-teacher }
  - { title: "CV", url: "/cv/", icon: file-pdf }

external: []


comments:
  # disqus_shortname: ""
  # isso_domain: ""

plugins:
  - jekyll-feed


