title: "Md M. Mamun"
author: "Md M. Mamun"
description: "University of Florida"
lang: "en"
permalink: /:title/
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: false
show_frame: true
show_sidebar: true
minimal: true   # dark/minimal header look (more professional)

# Menu
navigation:
  - { file: "about.md", title: "About", icon: user }
  - { file: "research.md", title: "Research", icon: book }
  - { file: "teaching.md", title: "Teaching", icon: chalkboard-teacher }
  - { file: "cv.md", title: "CV", icon: file-pdf }

external: []

comments:
  # disqus_shortname: ""
  # isso_domain: ""

plugins:
  - jekyll-feed
