title: "Md M. Mamun"
author: "Md M. Mamun"
description: "University of Florida"
lang: "en"
permalink: /:title/
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout
show_excerpts: false
show_frame: true
show_sidebar: true
minimal: true   # dark/minimal header look (more professional)

# Menu
navigation:
  - { file: "index.html", title: "Home", icon: home }
  - { file: "README.md", title: "About", icon: user }

external:
  - { title: Email, icon: envelope, url: "mailto:md.mamun@ufl.edu" }
  - { title: GitHub, icon: github, url: "https://github.com/mamun3210" }
  - { title: X, icon: x, url: "https://x.com/MdMMamun5" }

comments:
  # disqus_shortname: ""
  # isso_domain: ""

plugins:
  - jekyll-feed
